### ISSUE TITLE
Establish the initial content for the Registration API documentation

### ISSUE THREAD

**Issue by mw-dlr** [EOEPCA/resource-registration#2]

**Comment by mw-dlr** [comment]
As described here: https://github.com/EOEPCA/roadmap/issues/12

**Comment by kalxas** [comment]
The document now includes the initial content for the Registration API:
https://eoepca.readthedocs.io/projects/resource-registration/en/latest/design/registration-api/design/
https://eoepca.readthedocs.io/projects/resource-registration/en/latest/design/registration-api/api/endpoint-specification/
https://eoepca.readthedocs.io/projects/resource-registration/en/latest/design/registration-api/api/usage/

**Comment by kalxas** [comment]
I will close the issue after we review it

**Comment by kalxas** [comment]
Completed
