### ISSUE TITLE
Migrate Sentinel workflow BPMN to Flowable

### ISSUE THREAD

**Issue by mario-winkler** [EOEPCA/resource-registration#31]
### Description

Migrate the current terrabyte Camunda workflow BPMN for Sentinel data to Flowable. It is recommended to use the [Flowable Design](https://trial.flowable.com/design/) app to get a valid and deployable BPMN process.

### Acceptance criteria
- [x] The migrated BPMN model is available in the Harvester [workflows](https://github.com/EOEPCA/registration-harvester/tree/main/workflows)
- [x] A test is available showing that the migrated BPMN model can be deployed without errors at [Harvester API](https://registration-harvester-api.develop.eoepca.org/flowable-rest) in the develop-cluster

### Contributes to 
- https://github.com/EOEPCA/roadmap/issues/154
- https://github.com/EOEPCA/resource-registration/issues/9

**Comment by mw-dlr** [comment]
Is part of https://github.com/EOEPCA/resource-registration/issues/9

**Comment by mw-dlr** [comment]
This issue covers the migration of the _terrabyte_ workflow BPMN files to Flowable:
- [ ] sentinel-data-ingestion.bpmn
- [ ] data-order-sentinel-hourly.bpmn

It is recommended to use the [Flowable Design](https://trial.flowable.com/design/) app to get a valid and deployable BPMN process.

**Comment by mario-winkler** [comment]
The migrated BPMN processes are available in the repository:

- `workflows/sentinel-registration-hourly.bpmn`
![sentinel-registration-hourly](https://github.com/user-attachments/assets/a00c8eb0-cb5d-4186-b836-94d3a25ee65b)

- `workflows(sentinel-scene-ingestion.bpmn`
![sentinel-scene-ingestion](https://github.com/user-attachments/assets/cfb0383c-85b0-4b4b-9943-db26bd931c3b)

**Comment by mario-winkler** [comment]
A test that the migrated BPMN models can be deployed at the Flowable instance in the Dev-Cluster is documented as Jupyter notebook in https://github.com/EOEPCA/registration-harvester/blob/main/tests/test-sentinel-workflow.ipynb.

**Comment by mario-winkler** [comment]
Both acceptance criteria are met, issue can be closed.
