### ISSUE TITLE
V&V Plan with Github Actions CI/CD pipeline for Registration API (Q2)

### ISSUE THREAD

**Issue by kalxas** [EOEPCA/resource-registration#39]
Initial work for #27

**Comment by kalxas** [comment]
Created Registration API git repository
https://github.com/EOEPCA/registration-api

GitHub action is created for building the docker image.

**Comment by kalxas** [comment]
Setup of DockerHub image publication is pending (waiting for credentials)

**Comment by rconway** [comment]
Credentials for 'eoepca' DockerHub shared.

**Comment by kalxas** [comment]
Thank you @rconway 
The new registration api image has been published now:
https://hub.docker.com/r/eoepca/registration-api
